name: 'Publish AWS Lambda Layer'
description: 'Publish AWS Lambda Layer'
author: 'Dan Wilson'
inputs: 
  path:
    description: 'Path to zip file'
    required: true
runs:
  using: 'node12'
  main: 'lib/main.js'
