name: "Publish AWS Lambda Layer"
description: "Publish AWS Lambda Layer"
author: "Dan Wilson"
inputs:
  path:
    description: "Path to zip file"
    required: true
  bucket:
    description: "S3 bucket to upload to"
    required: true
  key:
    description: "S3 key to upload to"
    required: true
  layer:
    description: "Layer Name"
    required: true
  description:
    description: "Layer Description"
    required: true
  runtime:
    description: "AWS Lambda Runtime"
    required: false
    default: "python3.7"
  architecture:
    description: "AWS Lambda Architecture"
    required: false
    default: "x86_64"
runs:
  using: "node16"
  main: "dist/index.js"
